USE DW
DROP TABLE IF EXISTS FaMonitoring;
DROP TABLE IF EXISTS FaSatisfaction;
DROP TABLE IF EXISTS DimDate;
DROP TABLE IF EXISTS DimStudents;
DROP TABLE IF EXISTS DimClasses;
DROP TABLE IF EXISTS DimCourses;
DROP TABLE IF EXISTS DimSubjects;
DROP TABLE IF EXISTS DimTeachers;
