
DROP TABLE IF EXISTS Attendance;
DROP TABLE IF EXISTS Level_Of_Satisfaction;
DROP TABLE IF EXISTS Lessons;
DROP TABLE IF EXISTS Exams;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Subjects;
DROP TABLE IF EXISTS Classes;
DROP TABLE IF EXISTS Teachers;


DROP DATABASE IF EXISTS SchoolNEW;
