use SchoolNEW
GO
BULK INSERT Teachers FROM 'C:\Users\domin\PycharmProjects\pythonProject1\1TS\TeachersTS1.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Teachers FROM 'C:\Users\domin\PycharmProjects\pythonProject1\2TS\TeachersTS2.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Classes FROM 'C:\Users\domin\PycharmProjects\pythonProject1\2TS\ClassesTS2.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Classes FROM 'C:\Users\domin\PycharmProjects\pythonProject1\1TS\ClassesTS1.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Subjects FROM 'C:\Users\domin\PycharmProjects\pythonProject1\Subjects.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Courses FROM 'C:\Users\domin\PycharmProjects\pythonProject1\2TS\CourseTS2.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Courses FROM 'C:\Users\domin\PycharmProjects\pythonProject1\1TS\CourseTS1.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Students FROM 'C:\Users\domin\PycharmProjects\pythonProject1\2TS\StudentsTS1.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Students FROM 'C:\Users\domin\PycharmProjects\pythonProject1\1TS\StudentsTS2.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Exams FROM 'C:\Users\domin\PycharmProjects\pythonProject1\1TS\ExamsTS1.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Exams FROM 'C:\Users\domin\PycharmProjects\pythonProject1\2TS\ExamsTS2.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Lessons FROM 'C:\Users\domin\PycharmProjects\pythonProject1\1TS\LessonsTS1.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Lessons FROM 'C:\Users\domin\PycharmProjects\pythonProject1\2TS\LessonsTS2.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Level_Of_Satisfaction FROM 'C:\Users\domin\PycharmProjects\pythonProject1\1TS\SatisfactionTS1.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Level_Of_Satisfaction FROM 'C:\Users\domin\PycharmProjects\pythonProject1\2TS\SatisfactionTS2.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Attendance FROM 'C:\Users\domin\PycharmProjects\pythonProject1\1TS\AttendanceTS1.txt' WITH (FIELDTERMINATOR=',')
BULK INSERT Attendance FROM 'C:\Users\domin\PycharmProjects\pythonProject1\2TS\AttendanceTS2.txt' WITH (FIELDTERMINATOR=',')
